apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments
spec:
  selector:
    matchLabels:
      app: comments
  replicas: 1
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
      - name: comments
        image: rodneybarreto/minipets_comments-api:1.0.0
        imagePullPolicy: Always