apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rodneybarreto/minipets_frontend-app:1.1.0
        imagePullPolicy: Always
        env:       
        - name: PRODUCTS_HOST
          value: "$(PRODUCTS_SVC_SERVICE_HOST)"
        - name: PRODUCTS_PORT
          value: "$(PRODUCTS_SVC_SERVICE_PORT)"
        - name: SHIPPING_HOST
          value: "$(SHIPPING_SVC_SERVICE_HOST)"
        - name: SHIPPING_PORT
          value: "$(SHIPPING_SVC_SERVICE_PORT)"
        - name: COMMENTS_HOST
          value: "$(COMMENTS_SVC_SERVICE_HOST)"          
        - name: COMMENTS_PORT
          value: "$(COMMENTS_SVC_SERVICE_PORT)"