apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: rodneybarreto/minipets_products-api:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081