apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
spec:
  selector:
    matchLabels:
      app: shipping
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: rodneybarreto/minipets_shipping-api:1.0.0
        imagePullPolicy: Always